spring:

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/JavaUpMe
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
#    entity-manager-factory-interface: javax.persistence.EntityManagerFactory
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

server:
  port: 8011